apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/tracking-id: java-app:apps/Deployment::java-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
        - image: preyelg/java-backend:v1
          imagePullPolicy: IfNotPresent
          name: java-backend
          ports:
            - containerPort: 8080
