apiVersion: v1
kind: Service
metadata:
  name: java-backend
  namespace: default
spec:
  selector:
    app: java-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
