apiVersion: v1
kind: Service
metadata:
  name: java-backend
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/tracking-id: java-app:/Service::java-backend
spec:
  selector:
    app: java-backend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
